import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "on-tertiary-container": "#838688",
        outline: "#77767e",
        "surface-dim": "#cbdbf5",
        secondary: "#4648d4",
        "inverse-primary": "#c3c3eb",
        "primary-container": "#1a1b3a",
        "secondary-container": "#6063ee",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#47464e",
        "primary-fixed": "#e1e0ff",
        "on-background": "#0b1c30",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#5b5b7e",
        "surface-container-low": "#eff4ff",
        "outline-variant": "#c8c5ce",
        "on-tertiary-fixed": "#191c1e",
        primary: "#020220",
        "on-secondary": "#ffffff",
        "surface-container": "#e5eeff",
        "secondary-fixed-dim": "#c0c1ff",
        "on-primary-fixed": "#171837",
        tertiary: "#030507",
        "surface-container-high": "#dce9ff",
        "on-tertiary-fixed-variant": "#444749",
        "on-error-container": "#93000a",
        "on-secondary-container": "#fffbff",
        "primary-fixed-dim": "#c3c3eb",
        "tertiary-fixed-dim": "#c4c7c9",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#07006c",
        "inverse-surface": "#213145",
        "on-primary": "#ffffff",
        background: "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "on-primary-container": "#8383a8",
        "surface-variant": "#d3e4fe",
        "secondary-fixed": "#e1e0ff",
        "on-secondary-fixed-variant": "#2f2ebe",
        "tertiary-fixed": "#e0e3e5",
        "error-container": "#ffdad6",
        error: "#ba1a1a",
        "on-primary-fixed-variant": "#434465",
        surface: "#f8f9ff",
        "tertiary-container": "#1b1f21",
        "surface-container-highest": "#d3e4fe",
        "inverse-on-surface": "#eaf1ff",
        // probability pill colors (not in original design.md, added for Cascade)
        likely: "#1e7d3c",
        "likely-bg": "#d6f5e0",
        possible: "#a6650a",
        "possible-bg": "#fdf0d4",
        speculative: "#6d3aa8",
        "speculative-bg": "#ece0fb",
      },
      fontFamily: {
        sans: ["Hanken Grotesk", "sans-serif"],
        serif: ["Playfair Display", "serif"],
        "headline-lg": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "label-caps": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "display-xl": ["Hanken Grotesk"],
      },
      fontSize: {
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["36px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["20px", { lineHeight: "32px", fontWeight: "400" }],
        "display-xl": ["72px", { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "800" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "section-padding-lg": "160px",
        gutter: "32px",
        "container-max": "1280px",
        "margin-mobile": "24px",
        "section-padding-sm": "80px",
      },
      maxWidth: {
        container: "1280px",
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};

export default config;
